apiVersion: apps/v1
kind: Deployment
metadata:
  name: goodburguer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goodburguer
  template:
    metadata:
      labels:
        app: goodburguer
    spec:
      containers:
      - name: goodburguer
        image: felipecarvalhodesouza/goodburguer:latest
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: mysql-db-config
              key: DATABASE_URL
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-db-secret
              key: DATABASE_USERNAME
        - name: DATABASE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: mysql-db-config
              key: DATABASE_PASSWORD
        resources:
          requests:
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: goodburger-nodeport
spec:
  type: NodePort
  selector:
    app: goodburger
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 8080
