apiVersion: v1
kind: Service
metadata:
  name: goodburguer-service
  labels:
    app: goodburguer-app
spec:
  type: LoadBalancer
  selector:
    app: goodburguer-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080